name: Deploy Node.js App with Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build frontend
        run: npm run build

      - name: Deploy frontend to S3
        run: aws s3 sync ./dist s3://your-frontend-bucket-name

  deploy-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Start server
        run: pm2 restart server.js
